version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: sjhardware
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: .
    container_name: sjbackend
    environment:
      DATABASE_URL: postgresql://postgres:password1@db:5432/sjhardware
      SECRET_KEY: supersecretkey
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "
      until psql $DATABASE_URL -c '\q'; do
        echo 'Waiting for Postgres...';
        sleep 2;
      done;
      flask db upgrade &&
      gunicorn --bind 0.0.0.0:5000 --timeout 120 run:app
      "

volumes:
  pgdata:
